builds:
  - id: "casket"
    main: main.go
    dir: ./casket
    binary: casket
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
  # Build specifically for the Docker image with CGO disabled for MUSL compatibility
  - id: "docker"
    main: main.go
    dir: ./casket
    binary: casket
    env:
      - CGO_ENABLED=0
    goos: 
      - linux
    goarch:
      - amd64

dockers:
  - ids:
      - docker
    dockerfile: Dockerfile.release
    image_templates:
      - "gcr.io/tmpim/casket:latest"
      - "gcr.io/tmpim/casket:{{ .Tag }}"
      - "gcr.io/tmpim/casket:v{{ .Major }}"
      - "gcr.io/tmpim/casket:v{{ .Major }}.{{ .Minor }}"

# Set dist directory to build/ since we have files in dist/
dist: build

before:
  hooks:
    - sh ./.prerelease.sh

archives:
  - builds:
      - casket
    format_overrides:
      - goos: windows
        format: zip
checksum:
  algorithm: sha256

release:
  github:
    owner: tmpim
    name: casket
  ids:
    - casket
  draft: true
  prerelease: auto
